version: "3.8"

services:

  db:
    container_name: postgresql_db
    image: postgres:14
    restart: always
    volumes:
      - app-db-data:/var/lib/postgresql/data
    env_file:
      - .env_prod
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    expose:
      - 5432
    ports:
      - 5432:5432

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    env_file:
      - .env_prod
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD}
    expose:
      - 5050
    ports:
      - 5050:80
    depends_on:
      - db

  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: backend.dockerfile
    restart: always
    command: bash -c "alembic upgrade head && uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload --workers 1"
    env_file:
      - .env_prod
    volumes:
      - ./backend:/backend
    expose:
      - 8000
    ports:
      - 8000:8000
    depends_on:
      - db

  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: frontend_prod.dockerfile
    env_file:
      - .env
    expose:
      - 3000
    ports:
      - 3000:80
    environment:
      - CHOKIDAR_USEPOLLING=true

volumes:
  app-db-data: