version: "3.8"

services:

  db:
    container_name: postgresql_db
    image: postgres:14
    restart: always
    volumes:
      - app-db-data:/var/lib/postgresql/data
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - 5432:5432

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    env_file:
      - .env
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD}
    ports:
      - 5050:80
    depends_on:
      - db

  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: backend.dockerfile
    restart: always
<<<<<<< HEAD
    command: bash -c "alembic upgrade head && uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"
=======
    command: bash -c "alembic upgrade head && uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload --workers 1"
>>>>>>> refs/remotes/origin/FrontBeto
    env_file:
      - .env
    volumes:
      - ./backend:/backend
    ports:
      - 8000:8000
    depends_on:
      - db

  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: frontend.dockerfile
    restart: always
    command: ash -c "npm install && npm start"
    env_file:
      - .env
    volumes:
      - ./frontend/react-app:/frontend
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true

volumes:
  app-db-data: