"""layout and board

Revision ID: 03ae312e3cd6
Revises: 70f4e9adb7de
Create Date: 2022-10-13 22:21:57.084944

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03ae312e3cd6'
down_revision = '70f4e9adb7de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('layout',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('items', sa.JSON(), nullable=True),
    sa.Column('created_date', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_date', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_layout_id'), 'layout', ['id'], unique=False)
    op.create_index(op.f('ix_layout_name'), 'layout', ['name'], unique=True)
    op.create_table('board',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('layout_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('can_smoke', sa.Boolean(), nullable=True),
    sa.Column('position', sa.JSON(), nullable=True),
    sa.Column('qr', sa.String(), nullable=True),
    sa.Column('created_date', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_date', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['layout_id'], ['layout.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_board_id'), 'board', ['id'], unique=False)
    op.create_index(op.f('ix_board_name'), 'board', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_board_name'), table_name='board')
    op.drop_index(op.f('ix_board_id'), table_name='board')
    op.drop_table('board')
    op.drop_index(op.f('ix_layout_name'), table_name='layout')
    op.drop_index(op.f('ix_layout_id'), table_name='layout')
    op.drop_table('layout')
    # ### end Alembic commands ###
