"""Add tsvector in foods

Revision ID: 4a3aceddc90d
Revises: a5a023547953
Create Date: 2022-11-05 19:45:33.435600

"""
from alembic import op
import sqlalchemy as sa

from app.utils.sqlalchemy.custom_types import TSVector


# revision identifiers, used by Alembic.
revision = '4a3aceddc90d'
down_revision = 'a5a023547953'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('food', sa.Column('tsv', TSVector(), sa.Computed("to_tsvector('english',  name || ' ' ||  description)", persisted=True), nullable=True))
    op.create_index('idx_food_tsv', 'food', ['tsv'], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_food_tsv', table_name='food', postgresql_using='gin')
    op.drop_column('food', 'tsv')
    # ### end Alembic commands ###
