"""customer address table

Revision ID: 4cb7c156466b
Revises: b80b384c41ad
Create Date: 2022-10-20 21:19:51.559111

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4cb7c156466b'
down_revision = 'b80b384c41ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer_address',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('street', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('postal_code', sa.Integer(), nullable=True),
    sa.Column('location', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customer_address_customer_id'), 'customer_address', ['customer_id'], unique=False)
    op.create_index(op.f('ix_customer_address_id'), 'customer_address', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_customer_address_id'), table_name='customer_address')
    op.drop_index(op.f('ix_customer_address_customer_id'), table_name='customer_address')
    op.drop_table('customer_address')
    # ### end Alembic commands ###
