"""add new values to order table

Revision ID: 863c8bb8376a
Revises: 4a3aceddc90d
Create Date: 2022-11-19 17:45:37.577860

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '863c8bb8376a'
down_revision = '4a3aceddc90d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('note', sa.Text(), nullable=True))
    op.add_column('order_food', sa.Column('variant', sa.String(), nullable=True))
    op.add_column('order_food', sa.Column('unit', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order_food', 'unit')
    op.drop_column('order_food', 'variant')
    op.drop_column('order', 'note')
    # ### end Alembic commands ###
