"""Added settings table and color column in categories

Revision ID: 8910d87a27ab
Revises: 909100c5f8a3
Create Date: 2023-01-31 02:56:44.360368

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8910d87a27ab'
down_revision = '909100c5f8a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('setting',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('value', sa.JSON(), nullable=True),
    sa.Column('created_date', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_date', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_index(op.f('ix_setting_name'), 'setting', ['name'], unique=False)
    op.add_column('category', sa.Column('color', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('category', 'color')
    op.drop_index(op.f('ix_setting_name'), table_name='setting')
    op.drop_table('setting')
    # ### end Alembic commands ###
