"""Add new status in orders

Revision ID: 909100c5f8a3
Revises: 4cd452166063
Create Date: 2023-01-30 22:22:55.145214

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '909100c5f8a3'
down_revision = '4cd452166063'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('status_foods', sa.Boolean(), nullable=True))
    op.add_column('order', sa.Column('status_drinks', sa.Boolean(), nullable=True))
    op.add_column('order_food', sa.Column('status', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order_food', 'status')
    op.drop_column('order', 'status_drinks')
    op.drop_column('order', 'status_foods')
    # ### end Alembic commands ###
