"""User remove unique mobile

Revision ID: fb224e0e665c
Revises: 863c8bb8376a
Create Date: 2022-11-28 22:56:24.910877

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb224e0e665c'
down_revision = '863c8bb8376a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_mobile', table_name='user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_user_mobile', 'user', ['mobile'], unique=False)
    # ### end Alembic commands ###
