"""Add new columns in order table

Revision ID: fc2e3902c5c2
Revises: fb224e0e665c
Create Date: 2022-12-14 23:52:27.316524

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'fc2e3902c5c2'
down_revision = 'fb224e0e665c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    enum_types = postgresql.ENUM('restaurant', 'pick_up', 'shipment', name='typesorder')
    enum_types.create(op.get_bind(), checkfirst=True)
    op.add_column('order', sa.Column('order_type', enum_types, nullable=False))
    op.add_column('order', sa.Column('address', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order', 'address')
    op.drop_column('order', 'order_type')
    sa.Enum(name='typesorder').drop(op.get_bind(), checkfirst=False)
    # ### end Alembic commands ###
